### ISSUE TITLE
DX and Clean code review.

### ISSUE THREAD

**Issue by baldez300** [anttikup/suggestedimages#1]
README.md
The README file is concise and clear. However, there's a small typo in the "Run in development mode" section. The command should be:

            `flask run --app suggestedimages `

app.py
The app.py file is minimal but well-organized.

config.py
The config.py file is well-commented, making it easy to understand the purpose of each configuration parameter. I think it's necessary in this case.

pyproject.toml
The pyproject.toml file is straightforward and adheres to the standard setup.

requirements.txt
The requirements.txt file is well-structured and includes all necessary dependencies.

wd/api.py
The api.py file is comprehensive and seems well-structured. However, there's a small issue in the get_images_for_search function. The first argument should be an instance of StrInLanguage instead of a string. You should modify the function call in the __main__ block like this:

`print(get_images_for_search(StrInLanguage('rautatiesilta', lang='fi'), locale=Locale('fi'))) `

wd/queries.py
The queries.py file seems well-written.

wd/result.py
The result.py file looks good. The use of data classes is appropriate.

wd/util.py
The util.py file is extensive but well-organized. It's good practice to have utility functions for printing and building tooltips.

wd/init.py
The __init__.py file is simple and appropriately imports the get_images_for_search function.

wd/locales/fi.py
The fi.py file under locales is well-defined, and the translations are clear.

wd/locales/init.py
The __init__.py file in the locales package is good. It defines the languages and provides a way to access them.

tests/conftest.py
The conftest.py file is fine. It provides fixtures for testing, which is good practice.

tests/wd/test_app.py
The test_app.py file contains basic tests for the application configuration and a simple route. Consider expanding the test suite for more comprehensive coverage.

tests/wd/test_util.py
The test_util.py file includes tests for the utility functions. It's well-structured, and the test cases cover different scenarios.

suggestedimages/routes.py
The routes.py file is the main application logic. It's well-organized, and the route for the index page is appropriately defined.

suggestedimages/init.py
The __init__.py file for the Flask app is well-structured.

suggestedimages/static/index.js
The JavaScript file seems fine, focusing on handling DOM events.

Commit Analysis:
It seems, that commits are clear and concise on the history of the changes.
 
The codebase appears well-organized and follows best practices. Good job!

**Comment by anttikup** [comment]
Thanks for the review!
