### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by baldez300** [anttikup/suggestedimages#8]
The README.md file provides clear and concise instructions for setting up and running the image suggestion utility for Wiktionaries. The steps for creating a virtual environment, activating it, and installing requirements are well-documented. The inclusion of commands for running the application in development mode is also straightforward.

The bookmarklet section offers a useful addition for users, providing a JavaScript bookmarklet that opens search results for a Wiktionary page in a new tab. The code snippet for the bookmarklet is well-commented and explains its functionality.

However, it is important to note that the Pull Request has not been submitted for review separately.

**Comment by anttikup** [comment]
Thanks, for the review. I've been ill and didn't manage to finish the intended changes this week.
