### ISSUE TITLE
Exercise Week 6: Project Week 4 by valtat

### ISSUE THREAD

**Issue by valtat** [anttikup/suggestedimages#9]
I was supposed to review a pull request but seeing as there isn't one, I'll just do a brief summary here.

First impression, readme is straight to the point, not written for dummies, but informs all the necessary steps to start using the project. 

Project structure looks well made and clear, and there is additional information available, for example to external apis. Very nice.

I don't see any issues with the code or project, everything seems to be well documented and written. Only issue is the absence of the pull request for this week assignment.

**Comment by anttikup** [comment]
Thanks, for the review. I've been ill and didn't manage to finish the intended changes this week.
